import '@radix-ui/themes/styles.css';
import './theme-config.css';
import './globals.css';
import { Container, Theme } from '@radix-ui/themes';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from './components/NavBar';
import AuthProvider from './auth/Provider';

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Issue Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.variable}>
		<body >
      <AuthProvider>
        <Theme accentColor="cyan" grayColor="slate">
          <NavBar />
          <main className='p-5'>
            <Container  >
              {children}
            </Container>
          </main>
        </Theme>
      </AuthProvider>
		</body>
    </html>
  )
}
